import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import './globals.css'
import ThemeRegistry from './ThemeRegistry'
import ResponsiveAppBar from '../components/header/header';
import React from 'react';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }

export default function RootLayout(props: {children: React.ReactNode, unauthenticated: React.ReactNode, dashboard: React.ReactNode}) {
  // console.log(props);
  const { children, unauthenticated, dashboard } = props;
  // const [auth, setAuth] = React.useState(true);
  const auth = true; //await authCall();

  // React.useEffect(() => {
  //   //do auth call or cookie check here.
  //   setAuth(false);
  // },[]);
  return (
    <html lang="en">
      <body>
        {dashboard}
        <ThemeRegistry options={{ key: 'mui' }}>
        <ResponsiveAppBar></ResponsiveAppBar>
          {auth? children: unauthenticated}
        </ThemeRegistry>
      </body>
    </html>
  );
}